export const productos = [
    {
        id: 1,
        nombre: "Hamburguesa Clásica",
        precio: 11.99,
        descripcion: "Carne de res, queso cheddar, lechuga fresca, tomate jugoso, cebolla caramelizada y salsa secreta.",
        imagen: "/productos_img/burger_1.jpg",
        picante: true,
        vegano: false,
        destacado: true,
        favorito: false,
        ingredientes: ["ternera", "queso cheddar", "lechuga", "tomate", "cebolla caramelizada", "salsa secreta"],
        alergenos: ["gluten", "lacteos"],
        categoria: "hamburguesa"
    },
    {
        id: 2,
        nombre: "Hamburguesa BBQ",
        precio: 13.99,
        descripcion: "Carne de res, queso gouda, cebolla caramelizada, bacon crujiente y salsa barbacoa.",
        imagen: "/productos_img/burger_2.jpg",
        picante: false,
        vegano: false,
        destacado: false,
        favorito: true,
        ingredientes: ["ternera", "queso gouda", "cebolla caramelizada", "bacon crujiente", "salsa barbacoa"],
        alergenos: ["crustaceos", "lacteos"],
        categoria: "hamburguesa"
    },
    {
        id: 3,
        nombre: "Hamburguesa Vegana",
        precio: 10.99,
        descripcion: "Hamburguesa de lentejas, queso vegano, aguacate, lechuga y tomate fresco.",
        imagen: "/productos_img/burger_3.jpg",
        picante: false,
        vegano: true,
        destacado: false,
        favorito: false,
        ingredientes: ["lentejas", "queso vegano", "aguacate", "lechuga", "tomate fresco"],
        alergenos: ["huevos", "soja"],
        categoria: "hamburguesa"
    },
    {
        id: 4,
        nombre: "Hamburguesa Deluxe",
        precio: 15.99,
        descripcion: "Carne de res, queso azul, champiñones salteados, cebolla caramelizada y mayonesa trufada.",
        imagen: "/productos_img/burger_4.jpg",
        picante: true,
        vegano: false,
        destacado: false,
        favorito: true,
        ingredientes: ["ternera", "queso azul", "champiñones", "cebolla caramelizada", "mayonesa trufada"],
        alergenos: ["gluten", "lacteos"],
        categoria: "hamburguesa"
    },
    {
        id: 5,
        nombre: "Hamburguesa Hawaiana",
        precio: 14.99,
        descripcion: "Carne de res, piña fresca, queso suizo, bacon y salsa teriyaki.",
        imagen: "/productos_img/burger_5.jpg",
        picante: false,
        vegano: true,
        destacado: false,
        favorito: false,
        ingredientes: ["ternera", "piña", "queso suizo", "bacon", "salsa teriyaki"],
        alergenos: ["gluten", "lacteos"],
        categoria: "hamburguesa"
    },
    {
        id: 6,
        nombre: "Hamburguesa Picante",
        precio: 12.99,
        descripcion: "Carne de res, queso pepper jack, jalapeños, guacamole y salsa picante.",
        imagen: "/productos_img/burger_6.jpg",
        picante: true,
        vegano: false,
        destacado: false,
        favorito: false,
        ingredientes: ["ternera", "queso pepper jack", "jalapeños", "guacamole", "salsa picante"],
        alergenos: ["lacteos"],
        categoria: "hamburguesa"
    },
    {
        id: 7,
        nombre: "Hamburguesa de Pescado",
        precio: 16.99,
        descripcion: "Filete de pescado rebozado, queso americano, lechuga, tomate y salsa tártara.",
        imagen: "/productos_img/burger_7.jpg",
        picante: false,
        vegano: false,
        destacado: false,
        favorito: false,
        ingredientes: ["filete de pescado rebozado", "queso americano", "lechuga", "tomate", "salsa tártara"],
        alergenos: ["gluten", "lacteos", "pescado"],
        categoria: "hamburguesa"
    },
    {
        id: 8,
        nombre: "Hamburguesa Ranchera",
        precio: 13.99,
        descripcion: "Carne de res, queso cheddar, bacon, huevo frito, lechuga y salsa ranch.",
        imagen: "/productos_img/burger_8.jpg",
        picante: false,
        vegano: false,
        destacado: false,
        favorito: false,
        ingredientes: ["ternera", "queso cheddar", "bacon", "huevo frito", "lechuga", "salsa ranch"],
        alergenos: ["gluten", "lacteos"],
        categoria: "hamburguesa"
    },
    {
        id: 9,
        nombre: "Hamburguesa Mediterránea",
        precio: 14.99,
        descripcion: "Carne de cordero, queso feta, aceitunas, tomate seco y salsa de yogur.",
        imagen: "/productos_img/burger_9.jpg",
        picante: false,
        vegano: false,
        destacado: false,
        favorito: false,
        ingredientes: ["carne de cordero", "queso feta", "aceitunas", "tomate seco", "salsa de yogur"],
        alergenos: ["gluten", "lacteos"],
        categoria: "hamburguesa"
    },
    {
        id: 10,
        nombre: "Hamburguesa de Pollo BBQ",
        precio: 11.99,
        descripcion: "Pechuga de pollo a la parrilla, queso cheddar, cebolla caramelizada y salsa barbacoa.",
        imagen: "/productos_img/burger_1.jpg",
        picante: false,
        vegano: false,
        destacado: false,
        favorito: false,
        ingredientes: ["pechuga de pollo a la parrilla", "queso cheddar", "cebolla caramelizada", "salsa barbacoa"],
        alergenos: ["gluten", "lacteos"],
        categoria: "hamburguesa"
    },
    {
        id: 11,
        nombre: "Hamburguesa de Queso Azul",
        precio: 12.99,
        descripcion: "Carne de res, queso azul, cebolla morada, lechuga y mayonesa de queso azul.",
        imagen: "/productos_img/burger_2.jpg",
        picante: false,
        vegano: false,
        destacado: false,
        favorito: false,
        ingredientes: ["ternera", "queso azul", "cebolla morada", "lechuga", "mayonesa de queso azul"],
        alergenos: ["gluten", "lacteos"],
        categoria: "hamburguesa"
    },
    {
        id: 12,
        nombre: "Hamburguesa Tex-Mex",
        precio: 13.99,
        descripcion: "Carne de res, queso cheddar, guacamole, jalapeños y salsa chipotle.",
        imagen: "/productos_img/burger_3.jpg",
        picante: false,
        vegano: false,
        destacado: false,
        favorito: false,
        ingredientes: ["ternera", "queso cheddar", "guacamole", "jalapeños", "salsa chipotle"],
        alergenos: ["gluten", "lacteos"],
        categoria: "hamburguesa"
    },
    {
        id: 13,
        nombre: "Hamburguesa de Salmón",
        precio: 15.99,
        descripcion: "Filete de salmón a la parrilla, queso crema, alcaparras, lechuga y tomate.",
        imagen: "/productos_img/burger_4.jpg",
        picante: false,
        vegano: false,
        destacado: false,
        favorito: false,
        ingredientes: ["filete de salmón a la parrilla", "queso crema", "alcaparras", "lechuga", "tomate"],
        alergenos: ["pescado", "lacteos"],
        categoria: "hamburguesa"
    },
    {
        id: 14,
        nombre: "Hamburguesa de Pavo",
        precio: 11.99,
        descripcion: "Pechuga de pavo, queso suizo, aguacate, lechuga y mayonesa de mostaza y miel.",
        imagen: "/productos_img/burger_5.jpg",
        picante: false,
        vegano: false,
        destacado: false,
        favorito: false,
        ingredientes: ["pechuga de pavo", "queso suizo", "aguacate", "lechuga", "mayonesa de mostaza y miel"],
        alergenos: ["lacteos"],
        categoria: "hamburguesa"
    },
    {
        id: 15,
        nombre: "Hamburguesa de Garbanzos",
        precio: 10.99,
        descripcion: "Hamburguesa de garbanzos, hummus, pepino, tomate y lechuga.",
        imagen: "/productos_img/burger_6.jpg",
        picante: false,
        vegano: true,
        destacado: false,
        favorito: false,
        ingredientes: ["garbanzos", "hummus", "pepino", "tomate", "lechuga"],
        alergenos: ["sesamo"],
        categoria: "hamburguesa"
    }
];
